# Generated by Django 5.1.3 on 2024-11-25 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LotteryNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_number', models.CharField(max_length=20, unique=True, verbose_name='期号')),
                ('red_ball_1', models.IntegerField(verbose_name='红球1')),
                ('red_ball_2', models.IntegerField(verbose_name='红球2')),
                ('red_ball_3', models.IntegerField(verbose_name='红球3')),
                ('red_ball_4', models.IntegerField(verbose_name='红球4')),
                ('red_ball_5', models.IntegerField(verbose_name='红球5')),
                ('red_ball_6', models.IntegerField(verbose_name='红球6')),
                ('blue_ball', models.IntegerField(verbose_name='蓝球')),
                ('draw_date', models.DateTimeField(auto_now_add=True, verbose_name='开奖时间')),
            ],
            options={
                'verbose_name': '开奖号码',
                'verbose_name_plural': '开奖号码',
                'ordering': ['-issue_number'],
            },
        ),
    ]
